version: '3.8'

services:
  # Golang application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-chat-app
    restart: always
    environment:
      DATABASE_URL: "postgres://postgres:your-super-secret-and-long-postgres-password@host.docker.internal:5432/postgres"
    ports:
      - "3000:3000"
